// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeV_fSrUGOw5Or2y4CssYLUfJBW3l4J5o',
    appId: '1:607879466969:web:8577735b17f6eeef5513c8',
    messagingSenderId: '607879466969',
    projectId: 'feedbackapp-6c4e3',
    authDomain: 'feedbackapp-6c4e3.firebaseapp.com',
    storageBucket: 'feedbackapp-6c4e3.appspot.com',
    measurementId: 'G-P5JM5LD9SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJe60eOK0Q-0CAJpAkMCy102VF4l9tDw',
    appId: '1:607879466969:android:e7227f417f156a615513c8',
    messagingSenderId: '607879466969',
    projectId: 'feedbackapp-6c4e3',
    storageBucket: 'feedbackapp-6c4e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvo4i3qobWhuLBUuXQ988C8k6Qc3XK6pU',
    appId: '1:607879466969:ios:56676901a9a21e4c5513c8',
    messagingSenderId: '607879466969',
    projectId: 'feedbackapp-6c4e3',
    storageBucket: 'feedbackapp-6c4e3.appspot.com',
    iosBundleId: 'com.example.feedbackapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvo4i3qobWhuLBUuXQ988C8k6Qc3XK6pU',
    appId: '1:607879466969:ios:a693882edec9afec5513c8',
    messagingSenderId: '607879466969',
    projectId: 'feedbackapp-6c4e3',
    storageBucket: 'feedbackapp-6c4e3.appspot.com',
    iosBundleId: 'com.example.feedbackapp.RunnerTests',
  );
}
